baseURL = 'https://socketo.github.io'
title = "socketo's blog"
languageCode = 'ja'
theme = 'PaperMod'
author = 'socketo'

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]
  page = ["HTML"]

[params]
env = "production"
description = "デジタルフォレンジクスとセキュリティエンジニアリングに関する技術ブログ"
images = ["images/ogp.png"]
ShowReadingTime = true
ShowShareButtons = true
ShowToc = true
TocOpen = true

[params.homeInfoParams]
title = "Hi, I'm socketo"
Content = 'Digital Forensics Analyst | Security Engineer'

[params.assets]
favicon = "images/favicon.ico"

[[params.socialIcons]]
name = "github"
url = "https://github.com/socketo"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/sys_socket"

[[params.socialIcons]]
name = "linkedin"
url = "https://jp.linkedin.com/in/shigefumi-sakata-8a3978299"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
    name = "Archives"
    weight = 10
    identifier = "archives"
    url = "/archives"

[[menu.main]]
    name = "Tags"
    weight = 20
    identifier = "tags"
    url = "/tags"

[[menu.main]]
    name = "About"
    weight = 30
    identifier = "about"
    url = "/about"

[[menu.main]]
    name = "Search"
    weight = 40
    identifier = "search"
    url = "/search"
