baseURL = 'https://socketo.github.io'
title = "socketo's blog"
languageCode = 'ja'
theme = 'hugo-theme-m10c'
author = 'socketo'

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
author = "socketo"
description = "Digital Forensics Analyst | Security Engineer"
avatar = "images/avatar.png"

[params.style]
  darkestColor = "#0c1b30"
  darkColor = "#1a2f4a"
  lightColor = "#8eb0cc"
  lightestColor = "#e0f0ff"
  primaryColor = "#5bc8f5"

[[params.social]]
icon = "brand-github"
name = "GitHub"
url = "https://github.com/socketo"

[[params.social]]
icon = "brand-x"
name = "X (Twitter)"
url = "https://twitter.com/sys_socket"

[[params.social]]
icon = "brand-linkedin"
name = "LinkedIn"
url = "https://jp.linkedin.com/in/shigefumi-sakata-8a3978299"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
    name = "Tags"
    weight = 10
    identifier = "tags"
    url = "/tags"

[[menu.main]]
    name = "About"
    weight = 20
    identifier = "about"
    url = "/about"
